package ch.ethz.seb.sebserver.gbl.model;

import javax.annotation.Generated;

/** Defines the global names of the domain model and domain model fields.
* This shall be used as a static overall domain model names reference within SEB Server Web-Service as well as within the integrated GUI
* This file is generated by the org.eth.demo.sebserver.gen.DomainModelNameReferencePlugin and must not be edited manually.**/
@Generated(value="org.mybatis.generator.api.MyBatisGenerator",comments="ch.ethz.seb.sebserver.gen.DomainModelNameReferencePlugin",date="2018-12-03T08:25:17.226+01:00")
public interface Domain {

    interface CONFIGURATION_ATTRIBUTE {
        String ENITIY_NAME = "ConfigurationAttribute";
        String REFERENCE_NAME = "configurationAttributes";
        String ATTR_NAME = "name";
        String ATTR_TYPE = "type";
        String ATTR_PARENT_ID = "parentId";
        String ATTR_RESOURCES = "resources";
        String ATTR_VALIDATOR = "validator";
        String ATTR_DEPENDENCIES = "dependencies";
        String ATTR_DEFAULT_VALUE = "defaultValue";
    }

    interface CONFIGURATION_VALUE {
        String ENITIY_NAME = "ConfigurationValue";
        String REFERENCE_NAME = "configurationValues";
        String ATTR_CONFIGURATION_ID = "configurationId";
        String ATTR_CONFIGURATION_ATTRIBUTE_ID = "configurationAttributeId";
        String ATTR_LIST_INDEX = "listIndex";
        String ATTR_VALUE = "value";
    }

    interface ORIENTATION {
        String ENITIY_NAME = "Orientation";
        String REFERENCE_NAME = "orientations";
        String ATTR_CONFIG_ATTRIBUTE_ID = "configAttributeId";
        String ATTR_TEMPLATE = "template";
        String ATTR_VIEW = "view";
        String ATTR_GROUP = "group";
        String ATTR_X_POSITION = "xPosition";
        String ATTR_Y_POSITION = "yPosition";
        String ATTR_WIDTH = "width";
        String ATTR_HEIGHT = "height";
    }

    interface CONFIGURATION {
        String ENITIY_NAME = "Configuration";
        String REFERENCE_NAME = "configurations";
        String ATTR_CONFIGURATION_NODE_ID = "configurationNodeId";
        String ATTR_VERSION = "version";
        String ATTR_VERSION_DATE = "versionDate";
        String ATTR_FOLLOWUP = "followup";
    }

    interface CONFIGURATION_NODE {
        String ENITIY_NAME = "ConfigurationNode";
        String REFERENCE_NAME = "configurationNodes";
        String ATTR_INSTITUTION_ID = "institutionId";
        String ATTR_OWNER = "owner";
        String ATTR_NAME = "name";
        String ATTR_DESCRIPTION = "description";
        String ATTR_TYPE = "type";
        String ATTR_TEMPLATE = "template";
        String ATTR_ACTIVE = "active";
    }

    interface EXAM_CONFIGURATION_MAP {
        String ENITIY_NAME = "ExamConfigurationMap";
        String REFERENCE_NAME = "examConfigurationMaps";
        String ATTR_EXAM_ID = "examId";
        String ATTR_CONFIGURATION_NODE_ID = "configurationNodeId";
        String ATTR_USER_NAMES = "userNames";
    }

    interface EXAM {
        String ENITIY_NAME = "Exam";
        String REFERENCE_NAME = "exams";
        String ATTR_LMS_SETUP_ID = "lmsSetupId";
        String ATTR_EXTERNAL_UUID = "externalUuid";
        String ATTR_OWNER = "owner";
        String ATTR_SUPPORTER = "supporter";
        String ATTR_TYPE = "type";
        String ATTR_ACTIVE = "active";
    }

    interface CLIENT_CONNECTION {
        String ENITIY_NAME = "ClientConnection";
        String REFERENCE_NAME = "clientConnections";
        String ATTR_EXAM_ID = "examId";
        String ATTR_STATUS = "status";
        String ATTR_CONNECTION_TOKEN = "connectionToken";
        String ATTR_USER_NAME = "userName";
        String ATTR_VDI = "vdi";
        String ATTR_CLIENT_ADDRESS = "clientAddress";
        String ATTR_VIRTUAL_CLIENT_ADDRESS = "virtualClientAddress";
    }

    interface CLIENT_EVENT {
        String ENITIY_NAME = "ClientEvent";
        String REFERENCE_NAME = "clientEvents";
        String ATTR_CONNECTION_ID = "connectionId";
        String ATTR_USER_IDENTIFIER = "userIdentifier";
        String ATTR_TYPE = "type";
        String ATTR_TIMESTAMP = "timestamp";
        String ATTR_NUMERIC_VALUE = "numericValue";
        String ATTR_TEXT = "text";
    }

    interface INDICATOR {
        String ENITIY_NAME = "Indicator";
        String REFERENCE_NAME = "indicators";
        String ATTR_EXAM_ID = "examId";
        String ATTR_TYPE = "type";
        String ATTR_NAME = "name";
        String ATTR_COLOR = "color";
    }

    interface INSTITUTION {
        String ENITIY_NAME = "Institution";
        String REFERENCE_NAME = "institutions";
        String ATTR_NAME = "name";
        String ATTR_AUTHTYPE = "authtype";
        String ATTR_ACTIVE = "active";
    }

    interface LMS_SETUP {
        String ENITIY_NAME = "LmsSetup";
        String REFERENCE_NAME = "lmsSetups";
        String ATTR_INSTITUTION_ID = "institutionId";
        String ATTR_NAME = "name";
        String ATTR_LMS_TYPE = "lmsType";
        String ATTR_LMS_URL = "lmsUrl";
        String ATTR_LMS_CLIENTNAME = "lmsClientname";
        String ATTR_LMS_CLIENTSECRET = "lmsClientsecret";
        String ATTR_LMS_REST_API_TOKEN = "lmsRestApiToken";
        String ATTR_SEB_CLIENTNAME = "sebClientname";
        String ATTR_SEB_CLIENTSECRET = "sebClientsecret";
        String ATTR_ACTIVE = "active";
    }

    interface USER {
        String ENITIY_NAME = "User";
        String REFERENCE_NAME = "users";
        String ATTR_INSTITUTION_ID = "institutionId";
        String ATTR_UUID = "uuid";
        String ATTR_NAME = "name";
        String ATTR_USER_NAME = "userName";
        String ATTR_PASSWORD = "password";
        String ATTR_EMAIL = "email";
        String ATTR_LOCALE = "locale";
        String ATTR_TIMEZONE = "timezone";
        String ATTR_ACTIVE = "active";
    }

    interface USER_ROLE {
        String ENITIY_NAME = "UserRole";
        String REFERENCE_NAME = "userRoles";
        String ATTR_USER_ID = "userId";
        String ATTR_ROLE_NAME = "roleName";
    }

    interface USER_LOG {
        String ENITIY_NAME = "UserLog";
        String REFERENCE_NAME = "userLogs";
        String ATTR_USER_UUID = "userUuid";
        String ATTR_TIMESTAMP = "timestamp";
        String ATTR_ACTION_TYPE = "actionType";
        String ATTR_ENTITY_TYPE = "entityType";
        String ATTR_ENTITY_ID = "entityId";
        String ATTR_MESSAGE = "message";
    }
}