package ch.ethz.seb.sebserver.gbl.model;

import javax.annotation.Generated;

/** Defines the global names of the domain model and domain model fields.
* This shall be used as a static overall domain model names reference within SEB Server Web-Service as well as within the integrated GUI
* This file is generated by the org.eth.demo.sebserver.gen.DomainModelNameReferencePlugin and must not be edited manually.**/
@Generated(value="org.mybatis.generator.api.MyBatisGenerator",comments="ch.ethz.seb.sebserver.gen.DomainModelNameReferencePlugin",date="2018-11-26T12:04:08.096+01:00")
interface Domain {

    interface ConfigurationAttribute {
        String ENITIY_NAME = "ConfigurationAttribute";
        String ATTR_NAME = "name";
        String ATTR_TYPE = "type";
        String ATTR_PARENT_ID = "parentId";
        String ATTR_RESOURCES = "resources";
        String ATTR_VALIDATOR = "validator";
        String ATTR_DEPENDENCIES = "dependencies";
        String ATTR_DEFAULT_VALUE = "defaultValue";
    }

    interface ConfigurationValue {
        String ENITIY_NAME = "ConfigurationValue";
        String ATTR_CONFIGURATION_ID = "configurationId";
        String ATTR_CONFIGURATION_ATTRIBUTE_ID = "configurationAttributeId";
        String ATTR_LIST_INDEX = "listIndex";
        String ATTR_VALUE = "value";
    }

    interface Orientation {
        String ENITIY_NAME = "Orientation";
        String ATTR_CONFIG_ATTRIBUTE_ID = "configAttributeId";
        String ATTR_TEMPLATE = "template";
        String ATTR_VIEW = "view";
        String ATTR_GROUP = "group";
        String ATTR_X_POSITION = "xPosition";
        String ATTR_Y_POSITION = "yPosition";
        String ATTR_WIDTH = "width";
        String ATTR_HEIGHT = "height";
    }

    interface Configuration {
        String ENITIY_NAME = "Configuration";
        String ATTR_CONFIGURATION_NODE_ID = "configurationNodeId";
        String ATTR_VERSION = "version";
        String ATTR_VERSION_DATE = "versionDate";
        String ATTR_FOLLOWUP = "followup";
    }

    interface ConfigurationNode {
        String ENITIY_NAME = "ConfigurationNode";
        String ATTR_INSTITUTION_ID = "institutionId";
        String ATTR_OWNER = "owner";
        String ATTR_NAME = "name";
        String ATTR_DESCRIPTION = "description";
        String ATTR_TYPE = "type";
        String ATTR_TEMPLATE = "template";
    }

    interface ExamConfigurationMap {
        String ENITIY_NAME = "ExamConfigurationMap";
        String ATTR_EXAM_ID = "examId";
        String ATTR_CONFIGURATION_NODE_ID = "configurationNodeId";
        String ATTR_USER_NAMES = "userNames";
    }

    interface Exam {
        String ENITIY_NAME = "Exam";
        String ATTR_LMS_SETUP_ID = "lmsSetupId";
        String ATTR_EXTERNAL_UUID = "externalUuid";
        String ATTR_OWNER = "owner";
        String ATTR_SUPPORTER = "supporter";
        String ATTR_TYPE = "type";
    }

    interface ClientConnection {
        String ENITIY_NAME = "ClientConnection";
        String ATTR_EXAM_ID = "examId";
        String ATTR_STATUS = "status";
        String ATTR_CONNECTION_TOKEN = "connectionToken";
        String ATTR_USER_NAME = "userName";
        String ATTR_VDI = "vdi";
        String ATTR_CLIENT_ADDRESS = "clientAddress";
        String ATTR_VIRTUAL_CLIENT_ADDRESS = "virtualClientAddress";
    }

    interface ClientEvent {
        String ENITIY_NAME = "ClientEvent";
        String ATTR_CONNECTION_ID = "connectionId";
        String ATTR_USER_IDENTIFIER = "userIdentifier";
        String ATTR_TYPE = "type";
        String ATTR_TIMESTAMP = "timestamp";
        String ATTR_NUMERIC_VALUE = "numericValue";
        String ATTR_TEXT = "text";
    }

    interface Indicator {
        String ENITIY_NAME = "Indicator";
        String ATTR_EXAM_ID = "examId";
        String ATTR_TYPE = "type";
        String ATTR_NAME = "name";
        String ATTR_COLOR = "color";
    }

    interface Institution {
        String ENITIY_NAME = "Institution";
        String ATTR_NAME = "name";
        String ATTR_AUTHTYPE = "authtype";
    }

    interface LmsSetup {
        String ENITIY_NAME = "LmsSetup";
        String ATTR_INSTITUTION_ID = "institutionId";
        String ATTR_NAME = "name";
        String ATTR_LMS_TYPE = "lmsType";
        String ATTR_LMS_URL = "lmsUrl";
        String ATTR_LMS_CLIENTNAME = "lmsClientname";
        String ATTR_LMS_CLIENTSECRET = "lmsClientsecret";
        String ATTR_LMS_REST_API_TOKEN = "lmsRestApiToken";
        String ATTR_SEB_CLIENTNAME = "sebClientname";
        String ATTR_SEB_CLIENTSECRET = "sebClientsecret";
    }

    interface User {
        String ENITIY_NAME = "User";
        String ATTR_INSTITUTION_ID = "institutionId";
        String ATTR_UUID = "uuid";
        String ATTR_NAME = "name";
        String ATTR_USER_NAME = "userName";
        String ATTR_PASSWORD = "password";
        String ATTR_EMAIL = "email";
        String ATTR_CREATION_DATE = "creationDate";
        String ATTR_ACTIVE = "active";
        String ATTR_LOCALE = "locale";
        String ATTR_TIMEZONE = "timezone";
    }

    interface UserRole {
        String ENITIY_NAME = "UserRole";
        String ATTR_USER_ID = "userId";
        String ATTR_ROLE_NAME = "roleName";
    }
}