/*
 * Copyright (c) 2021 ETH Zürich, IT Services
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 */

package ch.ethz.seb.sebserver.webservice.servicelayer.exam;

import ch.ethz.seb.sebserver.gbl.model.EntityKey;
import ch.ethz.seb.sebserver.gbl.model.PageSortOrder;
import ch.ethz.seb.sebserver.gbl.model.exam.*;
import ch.ethz.seb.sebserver.gbl.util.Result;
import org.apache.commons.lang3.StringUtils;

import java.util.*;
import java.util.function.Function;

public interface ExamTemplateService {

    /** Exam start-date placeholder for autogenerated exam configurations name and description texts */
    String VAR_START_DATE = "__startDate__";
    /** Exam current-date placeholder for autogenerated exam configurations name and description texts */
    String VAR_CURRENT_DATE = "__currentDate__";
    /** Exam exam-name placeholder for autogenerated exam configurations name and description texts */
    String VAR_EXAM_NAME = "__examName__";
    /** Exam exam-template-name placeholder for autogenerated exam configurations name and description texts */
    String VAR_EXAM_TEMPLATE_NAME = "__examTemplateName__";

    /** Default name text for autogenerated exam configurations */
    String DEFAULT_EXAM_CONFIG_NAME_TEMPLATE = VAR_START_DATE + " " + VAR_EXAM_NAME;
    /** Default description text for autogenerated exam configurations */
    String DEFAULT_EXAM_CONFIG_DESC_TEMPLATE =
            "This has automatically been created from the exam template: "
                    + VAR_EXAM_TEMPLATE_NAME + " at: "
                    + VAR_CURRENT_DATE;

    /** Adds the indicators that are defined by a exam template or
     * a default indicator that is defined by configuration to a given exam.
     *
     * @param exam The Exam to add the default indicator
     * @return Result refer to the Exam with added default indicator or to an error if happened */
    Result<Exam> addDefinedIndicators(Exam exam);

    /** Adds the client groups that are defined by a exam template
     *
     * @param exam The Exam to add the client groups
     * @return Result refer to the Exam with added client groups or to an error if happened */
    Result<Exam> addDefinedClientGroups(Exam exam);

    /** Initializes additional exam template attributes for a specified Exam on creation.
     *
     * @param exam The Exam to add the default indicator
     * @return Result refer to the created exam or to an error when happened */
    Result<Exam> initAdditionalTemplateAttributes(Exam exam);

    /** Initializes a pre defined exam configuration. The configuration template to create a exam configuration
     * is defined by a given linked exam template. This is used to create the exam configuration and automatically
     * link it to the newly created exam
     *
     * @param exam The Exam to create and add new exam configuration
     * @return Result refer to the created exam or to an error when happened */
    Result<Exam> initExamConfiguration(Exam exam);

    /** Applies the Exam Template screen proctoring settings to an imported Exam that has been imported with the template
     * The Exam Template is referenced by the Exam itself.
     *
     * @param exam The exam to apply the screen proctoring settings from Exam  related Exam Template.
     * @return Result refer to teh Exam with applied SPS settings */
    Result<Exam> applyScreenProctoringSettingsForExam(Exam exam);

    Result<ExamTemplate> createExamTemplateAdditionalData(Long createdTemplateId, ExamTemplate examTemplate);

    Result<ExamTemplate> saveAdditionalData(ExamTemplate examTemplate);

    Result<ExamTemplate> applyExamTemplateAdditionalData(ExamTemplate examTemplate);

    //void updateConfigurationTemplate(ExamTemplate examTemplate);

    /** Creates a new client group template
     *
     * @param clientGroupTemplate The ClientGroupTemplate refer also to the exam template (examTemplateId)
     * @return Result refer to the created ClientGroupTemplate or to an error when happened */
    Result<ClientGroupTemplate> createNewClientGroupTemplate(ClientGroupTemplate clientGroupTemplate);

    /** Saves an already existing client group template
     *
     * @param clientGroupTemplate The ClientGroupTemplate refer also to the exam template (examTemplateId)
     * @return Result refer to the saved ClientGroupTemplate or to an error when happened */
    Result<ClientGroupTemplate> saveClientGroupTemplate(ClientGroupTemplate clientGroupTemplate);

    /** Deletes an already existing client group template
     *
     * @param examTemplateId the ExamTemplate id where the specified ClientGroupTemplate shall be deleted from
     * @param clientGroupTemplateId the id of the ClientGroupTemplate to delete
     * @return Result refer to the EntityKey of the deleted ClientGroupTemplate or to an error when happened */
    Result<EntityKey> deleteClientGroupTemplate(String examTemplateId, String clientGroupTemplateId);

    /** Creates a IndicatorTemplate list sort function for a given sort parameter.
     *
     * @param sort Sort parameter (Indicator.FILTER_ATTR_NAME)
     * @return Sort function for a IndicatorTemplate list */
    static Function<Collection<IndicatorTemplate>, List<IndicatorTemplate>> indicatorTemplatePageSort(
            final String sort) {

        final String sortBy = PageSortOrder.decode(sort);
        return indicators -> {
            final List<IndicatorTemplate> list = new ArrayList<>(indicators);
            if (StringUtils.isBlank(sort)) {
                return list;
            }

            if (sortBy.equals(Indicator.FILTER_ATTR_NAME)) {
                list.sort(Comparator.comparing(indicator -> indicator.name));
            }

            if (PageSortOrder.DESCENDING == PageSortOrder.getSortOrder(sort)) {
                Collections.reverse(list);
            }
            return list;
        };
    }

    /** Creates a ClientGroupTemplate list sort function for a given sort parameter.
     *
     * @param sort Sort parameter (ClientGroupTemplate.FILTER_ATTR_NAME)
     * @return Sort function for a ClientGroupTemplate list */
    static Function<Collection<ClientGroupTemplate>, List<ClientGroupTemplate>> clientGroupTemplatePageSort(
            final String sort) {

        final String sortBy = PageSortOrder.decode(sort);
        return clientGroups -> {
            final List<ClientGroupTemplate> list = new ArrayList<>(clientGroups);
            if (StringUtils.isBlank(sort)) {
                return list;
            }

            if (sortBy.equals(ClientGroupTemplate.FILTER_ATTR_NAME)) {
                list.sort(Comparator.comparing(indicator -> indicator.name));
            }

            if (PageSortOrder.DESCENDING == PageSortOrder.getSortOrder(sort)) {
                Collections.reverse(list);
            }
            return list;
        };
    }

}
