package ch.ethz.seb.sebserver.webservice.batis.model;

import javax.annotation.Generated;

public class InstitutionRecord {
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2018-11-14T08:29:18.697+01:00", comments="Source field: institution.id")
    private Long id;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2018-11-14T08:29:18.697+01:00", comments="Source field: institution.name")
    private String name;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2018-11-14T08:29:18.697+01:00", comments="Source field: institution.authtype")
    private String authtype;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2018-11-14T08:29:18.697+01:00", comments="Source Table: institution")
    public InstitutionRecord(Long id, String name, String authtype) {
        this.id = id;
        this.name = name;
        this.authtype = authtype;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2018-11-14T08:29:18.697+01:00", comments="Source field: institution.id")
    public Long getId() {
        return id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2018-11-14T08:29:18.697+01:00", comments="Source field: institution.name")
    public String getName() {
        return name;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2018-11-14T08:29:18.698+01:00", comments="Source field: institution.authtype")
    public String getAuthtype() {
        return authtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table institution
     *
     * @mbg.generated Wed Nov 14 08:29:18 CET 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", authtype=").append(authtype);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table institution
     *
     * @mbg.generated Wed Nov 14 08:29:18 CET 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        InstitutionRecord other = (InstitutionRecord) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getAuthtype() == null ? other.getAuthtype() == null : this.getAuthtype().equals(other.getAuthtype()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table institution
     *
     * @mbg.generated Wed Nov 14 08:29:18 CET 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getAuthtype() == null) ? 0 : getAuthtype().hashCode());
        return result;
    }
}