package ch.ethz.seb.sebserver.gbl.api;

import javax.annotation.Generated;

@Generated(value="org.mybatis.generator.api.MyBatisGenerator",comments="ch.ethz.seb.sebserver.gen.DomainModelNameReferencePlugin",date="2024-10-30T11:40:34.601+01:00")
public enum EntityType {
    CONFIGURATION_ATTRIBUTE,
    CONFIGURATION_VALUE,
    VIEW,
    ORIENTATION,
    CONFIGURATION,
    CONFIGURATION_NODE,
    EXAM_CONFIGURATION_MAP,
    EXAM,
    EXAM_SEB_RESTRICTION,
    EXAM_PROCTOR_DATA,
    CLIENT_CONNECTION,
    REMOTE_PROCTORING_ROOM,
    SCREEN_PROCTORING_GROUP,
    CLIENT_EVENT,
    CLIENT_INSTRUCTION,
    INDICATOR,
    THRESHOLD,
    INSTITUTION,
    SEB_CLIENT_CONFIGURATION,
    LMS_SETUP,
    USER,
    USER_ROLE,
    USER_ACTIVITY_LOG,
    ADDITIONAL_ATTRIBUTES,
    WEBSERVICE_SERVER_INFO,
    CERTIFICATE,
    EXAM_TEMPLATE,
    BATCH_ACTION,
    CLIENT_INDICATOR,
    CLIENT_NOTIFICATION,
    CLIENT_GROUP,
    SEB_SECURITY_KEY_REGISTRY,
    ENTITY_PRIVILEGE,
    FEATURE_PRIVILEGE;
}