package ch.ethz.seb.sebserver.webservice.datalayer.batis.model;

import jakarta.annotation.Generated;

public class ConfigurationAttributeDeprecation {
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2026-05-11T14:20:08.100+02:00", comments="Source field: configuration_attribute_deprecation.id")
    private Long id;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2026-05-11T14:20:08.100+02:00", comments="Source field: configuration_attribute_deprecation.configuration_attribute_id")
    private Long configurationAttributeId;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2026-05-11T14:20:08.100+02:00", comments="Source Table: configuration_attribute_deprecation")
    public ConfigurationAttributeDeprecation(Long id, Long configurationAttributeId) {
        this.id = id;
        this.configurationAttributeId = configurationAttributeId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2026-05-11T14:20:08.100+02:00", comments="Source field: configuration_attribute_deprecation.id")
    public Long getId() {
        return id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2026-05-11T14:20:08.100+02:00", comments="Source field: configuration_attribute_deprecation.configuration_attribute_id")
    public Long getConfigurationAttributeId() {
        return configurationAttributeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table configuration_attribute_deprecation
     *
     * @mbg.generated Mon May 11 14:20:08 CEST 2026
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", configurationAttributeId=").append(configurationAttributeId);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table configuration_attribute_deprecation
     *
     * @mbg.generated Mon May 11 14:20:08 CEST 2026
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ConfigurationAttributeDeprecation other = (ConfigurationAttributeDeprecation) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getConfigurationAttributeId() == null ? other.getConfigurationAttributeId() == null : this.getConfigurationAttributeId().equals(other.getConfigurationAttributeId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table configuration_attribute_deprecation
     *
     * @mbg.generated Mon May 11 14:20:08 CEST 2026
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getConfigurationAttributeId() == null) ? 0 : getConfigurationAttributeId().hashCode());
        return result;
    }
}