package ch.ethz.seb.sebserver.webservice.datalayer.batis.model;

import javax.annotation.Generated;

public class ExamTemplateRecord {
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2021-08-30T16:41:06.836+02:00", comments="Source field: exam_template.id")
    private Long id;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2021-08-30T16:41:06.836+02:00", comments="Source field: exam_template.institution_id")
    private Long institutionId;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2021-08-30T16:41:06.836+02:00", comments="Source field: exam_template.configuration_template_id")
    private Long configurationTemplateId;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2021-08-30T16:41:06.836+02:00", comments="Source field: exam_template.name")
    private String name;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2021-08-30T16:41:06.836+02:00", comments="Source field: exam_template.description")
    private String description;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2021-08-30T16:41:06.836+02:00", comments="Source field: exam_template.indicator_templates")
    private String indicatorTemplates;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2021-08-30T16:41:06.837+02:00", comments="Source field: exam_template.exam_attributes")
    private String examAttributes;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2021-08-30T16:41:06.836+02:00", comments="Source Table: exam_template")
    public ExamTemplateRecord(Long id, Long institutionId, Long configurationTemplateId, String name, String description, String indicatorTemplates, String examAttributes) {
        this.id = id;
        this.institutionId = institutionId;
        this.configurationTemplateId = configurationTemplateId;
        this.name = name;
        this.description = description;
        this.indicatorTemplates = indicatorTemplates;
        this.examAttributes = examAttributes;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2021-08-30T16:41:06.836+02:00", comments="Source field: exam_template.id")
    public Long getId() {
        return id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2021-08-30T16:41:06.836+02:00", comments="Source field: exam_template.institution_id")
    public Long getInstitutionId() {
        return institutionId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2021-08-30T16:41:06.836+02:00", comments="Source field: exam_template.configuration_template_id")
    public Long getConfigurationTemplateId() {
        return configurationTemplateId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2021-08-30T16:41:06.836+02:00", comments="Source field: exam_template.name")
    public String getName() {
        return name;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2021-08-30T16:41:06.836+02:00", comments="Source field: exam_template.description")
    public String getDescription() {
        return description;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2021-08-30T16:41:06.837+02:00", comments="Source field: exam_template.indicator_templates")
    public String getIndicatorTemplates() {
        return indicatorTemplates;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2021-08-30T16:41:06.837+02:00", comments="Source field: exam_template.exam_attributes")
    public String getExamAttributes() {
        return examAttributes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_template
     *
     * @mbg.generated Mon Aug 30 16:41:06 CEST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", institutionId=").append(institutionId);
        sb.append(", configurationTemplateId=").append(configurationTemplateId);
        sb.append(", name=").append(name);
        sb.append(", description=").append(description);
        sb.append(", indicatorTemplates=").append(indicatorTemplates);
        sb.append(", examAttributes=").append(examAttributes);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_template
     *
     * @mbg.generated Mon Aug 30 16:41:06 CEST 2021
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ExamTemplateRecord other = (ExamTemplateRecord) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getInstitutionId() == null ? other.getInstitutionId() == null : this.getInstitutionId().equals(other.getInstitutionId()))
            && (this.getConfigurationTemplateId() == null ? other.getConfigurationTemplateId() == null : this.getConfigurationTemplateId().equals(other.getConfigurationTemplateId()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getDescription() == null ? other.getDescription() == null : this.getDescription().equals(other.getDescription()))
            && (this.getIndicatorTemplates() == null ? other.getIndicatorTemplates() == null : this.getIndicatorTemplates().equals(other.getIndicatorTemplates()))
            && (this.getExamAttributes() == null ? other.getExamAttributes() == null : this.getExamAttributes().equals(other.getExamAttributes()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_template
     *
     * @mbg.generated Mon Aug 30 16:41:06 CEST 2021
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getInstitutionId() == null) ? 0 : getInstitutionId().hashCode());
        result = prime * result + ((getConfigurationTemplateId() == null) ? 0 : getConfigurationTemplateId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getDescription() == null) ? 0 : getDescription().hashCode());
        result = prime * result + ((getIndicatorTemplates() == null) ? 0 : getIndicatorTemplates().hashCode());
        result = prime * result + ((getExamAttributes() == null) ? 0 : getExamAttributes().hashCode());
        return result;
    }
}