package ch.ethz.seb.sebserver.webservice.datalayer.batis.model;

import javax.annotation.Generated;

public class FeaturePrivilegeRecord {
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2024-04-16T08:47:55.141+02:00", comments="Source field: feature_privilege.id")
    private Long id;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2024-04-16T08:47:55.141+02:00", comments="Source field: feature_privilege.feature_id")
    private Long featureId;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2024-04-16T08:47:55.141+02:00", comments="Source field: feature_privilege.user_uuid")
    private String userUuid;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2024-04-16T08:47:55.141+02:00", comments="Source Table: feature_privilege")
    public FeaturePrivilegeRecord(Long id, Long featureId, String userUuid) {
        this.id = id;
        this.featureId = featureId;
        this.userUuid = userUuid;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2024-04-16T08:47:55.141+02:00", comments="Source field: feature_privilege.id")
    public Long getId() {
        return id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2024-04-16T08:47:55.141+02:00", comments="Source field: feature_privilege.feature_id")
    public Long getFeatureId() {
        return featureId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2024-04-16T08:47:55.141+02:00", comments="Source field: feature_privilege.user_uuid")
    public String getUserUuid() {
        return userUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feature_privilege
     *
     * @mbg.generated Tue Apr 16 08:47:55 CEST 2024
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", featureId=").append(featureId);
        sb.append(", userUuid=").append(userUuid);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feature_privilege
     *
     * @mbg.generated Tue Apr 16 08:47:55 CEST 2024
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        FeaturePrivilegeRecord other = (FeaturePrivilegeRecord) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getFeatureId() == null ? other.getFeatureId() == null : this.getFeatureId().equals(other.getFeatureId()))
            && (this.getUserUuid() == null ? other.getUserUuid() == null : this.getUserUuid().equals(other.getUserUuid()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feature_privilege
     *
     * @mbg.generated Tue Apr 16 08:47:55 CEST 2024
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getFeatureId() == null) ? 0 : getFeatureId().hashCode());
        result = prime * result + ((getUserUuid() == null) ? 0 : getUserUuid().hashCode());
        return result;
    }
}