package ch.ethz.seb.sebserver.webservice.datalayer.batis.model;

import jakarta.annotation.Generated;

public class ScheduledDeleteInfoRecord {
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2026-05-11T14:20:08.098+02:00", comments="Source field: scheduled_delete_info.id")
    private Long id;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2026-05-11T14:20:08.098+02:00", comments="Source field: scheduled_delete_info.scheduled_delete_id")
    private Long scheduledDeleteId;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2026-05-11T14:20:08.098+02:00", comments="Source field: scheduled_delete_info.state")
    private String state;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2026-05-11T14:20:08.098+02:00", comments="Source field: scheduled_delete_info.exam_uuid")
    private String examUuid;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2026-05-11T14:20:08.098+02:00", comments="Source field: scheduled_delete_info.deletion_info")
    private String deletionInfo;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2026-05-11T14:20:08.098+02:00", comments="Source field: scheduled_delete_info.error_info")
    private String errorInfo;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2026-05-11T14:20:08.098+02:00", comments="Source Table: scheduled_delete_info")
    public ScheduledDeleteInfoRecord(Long id, Long scheduledDeleteId, String state, String examUuid, String deletionInfo, String errorInfo) {
        this.id = id;
        this.scheduledDeleteId = scheduledDeleteId;
        this.state = state;
        this.examUuid = examUuid;
        this.deletionInfo = deletionInfo;
        this.errorInfo = errorInfo;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2026-05-11T14:20:08.098+02:00", comments="Source field: scheduled_delete_info.id")
    public Long getId() {
        return id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2026-05-11T14:20:08.098+02:00", comments="Source field: scheduled_delete_info.scheduled_delete_id")
    public Long getScheduledDeleteId() {
        return scheduledDeleteId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2026-05-11T14:20:08.098+02:00", comments="Source field: scheduled_delete_info.state")
    public String getState() {
        return state;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2026-05-11T14:20:08.098+02:00", comments="Source field: scheduled_delete_info.exam_uuid")
    public String getExamUuid() {
        return examUuid;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2026-05-11T14:20:08.098+02:00", comments="Source field: scheduled_delete_info.deletion_info")
    public String getDeletionInfo() {
        return deletionInfo;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2026-05-11T14:20:08.098+02:00", comments="Source field: scheduled_delete_info.error_info")
    public String getErrorInfo() {
        return errorInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scheduled_delete_info
     *
     * @mbg.generated Mon May 11 14:20:08 CEST 2026
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", scheduledDeleteId=").append(scheduledDeleteId);
        sb.append(", state=").append(state);
        sb.append(", examUuid=").append(examUuid);
        sb.append(", deletionInfo=").append(deletionInfo);
        sb.append(", errorInfo=").append(errorInfo);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scheduled_delete_info
     *
     * @mbg.generated Mon May 11 14:20:08 CEST 2026
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ScheduledDeleteInfoRecord other = (ScheduledDeleteInfoRecord) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getScheduledDeleteId() == null ? other.getScheduledDeleteId() == null : this.getScheduledDeleteId().equals(other.getScheduledDeleteId()))
            && (this.getState() == null ? other.getState() == null : this.getState().equals(other.getState()))
            && (this.getExamUuid() == null ? other.getExamUuid() == null : this.getExamUuid().equals(other.getExamUuid()))
            && (this.getDeletionInfo() == null ? other.getDeletionInfo() == null : this.getDeletionInfo().equals(other.getDeletionInfo()))
            && (this.getErrorInfo() == null ? other.getErrorInfo() == null : this.getErrorInfo().equals(other.getErrorInfo()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scheduled_delete_info
     *
     * @mbg.generated Mon May 11 14:20:08 CEST 2026
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getScheduledDeleteId() == null) ? 0 : getScheduledDeleteId().hashCode());
        result = prime * result + ((getState() == null) ? 0 : getState().hashCode());
        result = prime * result + ((getExamUuid() == null) ? 0 : getExamUuid().hashCode());
        result = prime * result + ((getDeletionInfo() == null) ? 0 : getDeletionInfo().hashCode());
        result = prime * result + ((getErrorInfo() == null) ? 0 : getErrorInfo().hashCode());
        return result;
    }
}