package ch.ethz.seb.sebserver.webservice.datalayer.batis.model;

import jakarta.annotation.Generated;

public class ScheduledDeleteRecord {
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2026-03-02T15:33:13.706+01:00", comments="Source field: scheduled_delete.id")
    private Long id;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2026-03-02T15:33:13.706+01:00", comments="Source field: scheduled_delete.sps_id")
    private Long spsId;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2026-03-02T15:33:13.706+01:00", comments="Source field: scheduled_delete.state")
    private String state;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2026-03-02T15:33:13.706+01:00", comments="Source field: scheduled_delete.delete_due_time")
    private Long deleteDueTime;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2026-03-02T15:33:13.706+01:00", comments="Source field: scheduled_delete.schedule_time")
    private Long scheduleTime;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2026-03-02T15:33:13.706+01:00", comments="Source field: scheduled_delete.start_time")
    private Long startTime;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2026-03-02T15:33:13.706+01:00", comments="Source field: scheduled_delete.end_time")
    private Long endTime;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2026-03-02T15:33:13.706+01:00", comments="Source field: scheduled_delete.owner")
    private String owner;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2026-03-02T15:33:13.706+01:00", comments="Source field: scheduled_delete.institution_id")
    private Long institutionId;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2026-03-02T15:33:13.706+01:00", comments="Source Table: scheduled_delete")
    public ScheduledDeleteRecord(Long id, Long spsId, String state, Long deleteDueTime, Long scheduleTime, Long startTime, Long endTime, String owner, Long institutionId) {
        this.id = id;
        this.spsId = spsId;
        this.state = state;
        this.deleteDueTime = deleteDueTime;
        this.scheduleTime = scheduleTime;
        this.startTime = startTime;
        this.endTime = endTime;
        this.owner = owner;
        this.institutionId = institutionId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2026-03-02T15:33:13.706+01:00", comments="Source field: scheduled_delete.id")
    public Long getId() {
        return id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2026-03-02T15:33:13.706+01:00", comments="Source field: scheduled_delete.sps_id")
    public Long getSpsId() {
        return spsId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2026-03-02T15:33:13.706+01:00", comments="Source field: scheduled_delete.state")
    public String getState() {
        return state;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2026-03-02T15:33:13.706+01:00", comments="Source field: scheduled_delete.delete_due_time")
    public Long getDeleteDueTime() {
        return deleteDueTime;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2026-03-02T15:33:13.706+01:00", comments="Source field: scheduled_delete.schedule_time")
    public Long getScheduleTime() {
        return scheduleTime;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2026-03-02T15:33:13.706+01:00", comments="Source field: scheduled_delete.start_time")
    public Long getStartTime() {
        return startTime;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2026-03-02T15:33:13.706+01:00", comments="Source field: scheduled_delete.end_time")
    public Long getEndTime() {
        return endTime;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2026-03-02T15:33:13.706+01:00", comments="Source field: scheduled_delete.owner")
    public String getOwner() {
        return owner;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2026-03-02T15:33:13.706+01:00", comments="Source field: scheduled_delete.institution_id")
    public Long getInstitutionId() {
        return institutionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scheduled_delete
     *
     * @mbg.generated Mon Mar 02 15:33:13 CET 2026
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", spsId=").append(spsId);
        sb.append(", state=").append(state);
        sb.append(", deleteDueTime=").append(deleteDueTime);
        sb.append(", scheduleTime=").append(scheduleTime);
        sb.append(", startTime=").append(startTime);
        sb.append(", endTime=").append(endTime);
        sb.append(", owner=").append(owner);
        sb.append(", institutionId=").append(institutionId);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scheduled_delete
     *
     * @mbg.generated Mon Mar 02 15:33:13 CET 2026
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ScheduledDeleteRecord other = (ScheduledDeleteRecord) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getSpsId() == null ? other.getSpsId() == null : this.getSpsId().equals(other.getSpsId()))
            && (this.getState() == null ? other.getState() == null : this.getState().equals(other.getState()))
            && (this.getDeleteDueTime() == null ? other.getDeleteDueTime() == null : this.getDeleteDueTime().equals(other.getDeleteDueTime()))
            && (this.getScheduleTime() == null ? other.getScheduleTime() == null : this.getScheduleTime().equals(other.getScheduleTime()))
            && (this.getStartTime() == null ? other.getStartTime() == null : this.getStartTime().equals(other.getStartTime()))
            && (this.getEndTime() == null ? other.getEndTime() == null : this.getEndTime().equals(other.getEndTime()))
            && (this.getOwner() == null ? other.getOwner() == null : this.getOwner().equals(other.getOwner()))
            && (this.getInstitutionId() == null ? other.getInstitutionId() == null : this.getInstitutionId().equals(other.getInstitutionId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scheduled_delete
     *
     * @mbg.generated Mon Mar 02 15:33:13 CET 2026
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getSpsId() == null) ? 0 : getSpsId().hashCode());
        result = prime * result + ((getState() == null) ? 0 : getState().hashCode());
        result = prime * result + ((getDeleteDueTime() == null) ? 0 : getDeleteDueTime().hashCode());
        result = prime * result + ((getScheduleTime() == null) ? 0 : getScheduleTime().hashCode());
        result = prime * result + ((getStartTime() == null) ? 0 : getStartTime().hashCode());
        result = prime * result + ((getEndTime() == null) ? 0 : getEndTime().hashCode());
        result = prime * result + ((getOwner() == null) ? 0 : getOwner().hashCode());
        result = prime * result + ((getInstitutionId() == null) ? 0 : getInstitutionId().hashCode());
        return result;
    }
}