package ch.ethz.seb.sebserver.webservice.datalayer.batis.model;

import javax.annotation.Generated;

public class SecurityKeyRegistryRecord {
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2022-11-03T16:28:08.513+01:00", comments="Source field: seb_security_key_registry.id")
    private Long id;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2022-11-03T16:28:08.513+01:00", comments="Source field: seb_security_key_registry.institution_id")
    private Long institutionId;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2022-11-03T16:28:08.513+01:00", comments="Source field: seb_security_key_registry.type")
    private String type;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2022-11-03T16:28:08.513+01:00", comments="Source field: seb_security_key_registry.key")
    private String key;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2022-11-03T16:28:08.513+01:00", comments="Source field: seb_security_key_registry.tag")
    private String tag;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2022-11-03T16:28:08.513+01:00", comments="Source field: seb_security_key_registry.exam_id")
    private Long examId;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2022-11-03T16:28:08.513+01:00", comments="Source field: seb_security_key_registry.exam_template_id")
    private Long examTemplateId;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2022-11-03T16:28:08.513+01:00", comments="Source field: seb_security_key_registry.encryption_type")
    private String encryptionType;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2022-11-03T16:28:08.513+01:00", comments="Source Table: seb_security_key_registry")
    public SecurityKeyRegistryRecord(Long id, Long institutionId, String type, String key, String tag, Long examId, Long examTemplateId, String encryptionType) {
        this.id = id;
        this.institutionId = institutionId;
        this.type = type;
        this.key = key;
        this.tag = tag;
        this.examId = examId;
        this.examTemplateId = examTemplateId;
        this.encryptionType = encryptionType;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2022-11-03T16:28:08.513+01:00", comments="Source field: seb_security_key_registry.id")
    public Long getId() {
        return id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2022-11-03T16:28:08.513+01:00", comments="Source field: seb_security_key_registry.institution_id")
    public Long getInstitutionId() {
        return institutionId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2022-11-03T16:28:08.513+01:00", comments="Source field: seb_security_key_registry.type")
    public String getType() {
        return type;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2022-11-03T16:28:08.513+01:00", comments="Source field: seb_security_key_registry.key")
    public String getKey() {
        return key;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2022-11-03T16:28:08.513+01:00", comments="Source field: seb_security_key_registry.tag")
    public String getTag() {
        return tag;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2022-11-03T16:28:08.513+01:00", comments="Source field: seb_security_key_registry.exam_id")
    public Long getExamId() {
        return examId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2022-11-03T16:28:08.513+01:00", comments="Source field: seb_security_key_registry.exam_template_id")
    public Long getExamTemplateId() {
        return examTemplateId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2022-11-03T16:28:08.513+01:00", comments="Source field: seb_security_key_registry.encryption_type")
    public String getEncryptionType() {
        return encryptionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seb_security_key_registry
     *
     * @mbg.generated Thu Nov 03 16:28:08 CET 2022
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", institutionId=").append(institutionId);
        sb.append(", type=").append(type);
        sb.append(", key=").append(key);
        sb.append(", tag=").append(tag);
        sb.append(", examId=").append(examId);
        sb.append(", examTemplateId=").append(examTemplateId);
        sb.append(", encryptionType=").append(encryptionType);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seb_security_key_registry
     *
     * @mbg.generated Thu Nov 03 16:28:08 CET 2022
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SecurityKeyRegistryRecord other = (SecurityKeyRegistryRecord) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getInstitutionId() == null ? other.getInstitutionId() == null : this.getInstitutionId().equals(other.getInstitutionId()))
            && (this.getType() == null ? other.getType() == null : this.getType().equals(other.getType()))
            && (this.getKey() == null ? other.getKey() == null : this.getKey().equals(other.getKey()))
            && (this.getTag() == null ? other.getTag() == null : this.getTag().equals(other.getTag()))
            && (this.getExamId() == null ? other.getExamId() == null : this.getExamId().equals(other.getExamId()))
            && (this.getExamTemplateId() == null ? other.getExamTemplateId() == null : this.getExamTemplateId().equals(other.getExamTemplateId()))
            && (this.getEncryptionType() == null ? other.getEncryptionType() == null : this.getEncryptionType().equals(other.getEncryptionType()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seb_security_key_registry
     *
     * @mbg.generated Thu Nov 03 16:28:08 CET 2022
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getInstitutionId() == null) ? 0 : getInstitutionId().hashCode());
        result = prime * result + ((getType() == null) ? 0 : getType().hashCode());
        result = prime * result + ((getKey() == null) ? 0 : getKey().hashCode());
        result = prime * result + ((getTag() == null) ? 0 : getTag().hashCode());
        result = prime * result + ((getExamId() == null) ? 0 : getExamId().hashCode());
        result = prime * result + ((getExamTemplateId() == null) ? 0 : getExamTemplateId().hashCode());
        result = prime * result + ((getEncryptionType() == null) ? 0 : getEncryptionType().hashCode());
        return result;
    }
}